version: "3"

services:
  server:
    build: server/
    ports:
      - 5001:5001

    image: loganwyas/library-project:server

    restart: always

  client:
    depends_on:
      - server

    image: loganwyas/library-project:client

    build: client/
    ports:
      - 3001:3001

    restart: always
