version: "3"
name: loganwyas/library-project

services:
  server:
    build: server/
    ports:
      - 5001:5001

    restart: always

  client:
    depends_on:
      - server

    image: nextjs-docker

    build: client/
    ports:
      - 3001:3001

    restart: always
