version: 2.1

jobs:
  build_client:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker build
          command: docker-compose build -t $DOCKERHUB_USERNAME/myapp:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: docker-compose push $DOCKERHUB_USERNAME/myapp:${CIRCLE_SHA1}

  build_server:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker build
          command: docker build -t $DOCKERHUB_USERNAME/myapp:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push $DOCKERHUB_USERNAME/myapp:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_client:
          filters:
            branches:
              - main
              - docker-pipeline
      - build_server:
          filters:
            branches:
              - main
              - docker-pipeline
