version: 2.1

jobs:
  run_tests:
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests.py
  build_app:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker build
          command: docker-compose build
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: docker-compose push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run_tests:
          filters:
            branches:
              only:
                - main
                - docker-pipeline
      - build_app:
          filters:
            branches:
              only:
                - main
                - docker-pipeline
          requires:
            - run_tests
