version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  run_tests:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: server/requirements.txt
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest server/tests.py

  build_app:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker build
          command: docker-compose build
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: docker-compose push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run_tests:
          filters:
            branches:
              only:
                - main
                - docker-pipeline
      - build_app:
          filters:
            branches:
              only:
                - main
                - docker-pipeline
          requires:
            - run_tests
