version: 2.1

jobs:
  build_app:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker build
          command: docker-compose build
      - run:
          name: Authenticate with Docker Hub
          command: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: docker-compose push ${{ secrets.DOCKERHUB_USERNAME }}/library-project:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_app:
          filters:
            branches:
              only:
                - main
                - docker-pipeline
