version: 2.1

orbs:
  python: circleci/python@2.1.1
  node: circleci/node@5.1.0

jobs:
  build_server:
    executor: python/default
    working_directory: ~/server
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: server/requirements.txt
          pkg-manager: pip

  build_client:
    executor: node/default
    working_directory: client
    steps:
      - checkout
      - node/install-packages:
          app-dir: client
          pkg-manager: npm
      - run:
          app-dir: client
          command: "npm run build"
      - store_artifacts:
          path: build

workflows:
  project-workflow:
    jobs:
      - build_server
      - build_client
