import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="top-0 bg-gray-400 p-6 flex flex-wrap space-x-7">
          <Link href="/">Home</Link>
          <Link href="/login">Login</Link>
        </nav>
        <div className="mt-8">{children}</div>
      </body>
    </html>
  );
}
